spring:
  application:
    name: HelpDesk
  profiles:
    active: Local
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        hbm2ddl:
          schema_filter_provider: com.nicico.copper.common.hibernate.CustomSchemaFilterProvider
    open-in-view: false
  liquibase:
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:db/changelog/liquibase-master.xml
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  activiti:
    rest-api-enabled: true
    history-level: full
    database-schema-update: true
    db-history-used: true
  redis:
    port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 8080
  servlet:
    context-path: /help-desk
    session:
      cookie:
        name: App_${spring.application.name}

management:
  endpoint:
    health:
      show-details: always

nicico:
  helpdesk:
    version: 1
  jpa:
    entity:
      package: com.nicico.helpdesk.model
  google:
    mail:
      username:
      password:
  mail:
    domain:
    url:
    username:
    password:
  upload:
    dir: /var/nicico/${spring.application.name}/
  workflow:
    update:
      mode: false
support:
  upload:
    dir: /var/nicico/${spring.application.name}/

---

spring:
  profiles: Production
  datasource:
    url: jdbc:oracle:thin:@//srv-oraprd1.nicico.com:1521/pdb_prd01
    username: n_helpdesk
    password: ENC(CiwmmfKPd/W8xhfO9rriKUHGQ7V/n48zV8/qVlJHvS0=)
  redis:
    host: apps.icico.net.ir
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: ENC(+ba6rtgG3bdB98o4Q3WLqxy2hfqTu0imiXKCtNSzT+U=)
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://apps.nicico.com/oauth/authorize
            token-uri: http://apps.nicico.com/oauth/token
            user-info-uri: http://apps.nicico.com/user/info
            user-name-attribute: username

---

spring:
  profiles: Development
  redis:
    host: devapp01.icico.net.ir
    password: nicico
  datasource:
    url: jdbc:oracle:thin:@//oragnrt01.icico.net.ir:1521/pdb_dev01
    username: helpdesk
    password: helpdesk
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://devapp01.icico.net.ir/oauth/authorize
            token-uri: http://devapp01.icico.net.ir/oauth/token
            user-info-uri: http://devapp01.icico.net.ir/user/info
            user-name-attribute: username

---

spring:
  profiles: Local
  redis:
    host: devapp01.icico.net.ir
    password: nicico
  datasource:
    url: jdbc:oracle:thin:@//oragnrt01.icico.net.ir:1521/pdb_dev01
    username: helpdesk
    password: helpdesk
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://devapp01.icico.net.ir/oauth/authorize
            token-uri: http://devapp01.icico.net.ir/oauth/token
            user-info-uri: http://devapp01.icico.net.ir/user/info
            user-name-attribute: username
support:
  upload:
    dir: c:/var/nicico/${spring.application.name}/